[package]
authors = ["The Animal Time Team"]
description = "An adjectived animal for each minute until the year 2046."
edition = "2021"
license = "MIT OR Apache-2.0 OR CC0-1.0"
name = "animal-time"
version = "0.1.0"

[dependencies]
