name: ci

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - run: cargo build --release

      - run: echo "BUILD_ID=$(target/release/animal-time)" >> $GITHUB_ENV

      - id: create_release
        uses: trevyn/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.BUILD_ID }}
          draft: false
          prerelease: false
          files: target/release/animal-time